### ISSUE TITLE
fix hash default is 4GB as . in the max

### ISSUE THREAD

**Issue by greenbean52** [ehsanrashid/DON#6]
uci
option name Hash type spin default 16 min 0 max 3.35544e+07

you can clearly see the problem it should be 335544e07  much be some late night coding as easy fix just a typo, I hope.
also in uci no hash setting options

setoption name hash value 1024 
does not have the desired effect.
it puts it at 216MB when vs its self

this one is a winner;
if you could also implement NN learning
perhaps put some romichess book learning positon learning logic to it;
crafty is just not learning fast enough.

deriving from glaurung 21 as 22 was not as strong can only be a good thing! 👍 
but have noticed that Glaurung201-64 is the strongest of Glaurung builds 201 is not the same as 21; 201 is stronger than 2.1 or 21;
have tested all;
so deriving from Glaurung201-64 is even better as some bits may have been missed out as 21 or 2.1 is not the strongest;
so maybe looking adding that 121 + 21 or 201 +2.1 version code logic to DON
🥇 DON is an upcoming champ!

so would like to focus my efforts on this build with .lrn merging included also.
look forward to the next DON release!

cheers!
Greenbean

**Comment by ehsanrashid** [comment]
This issue has been resolved.
